# Generated by Django 4.1.6 on 2023-02-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('template', models.ImageField(upload_to='course_images')),
            ],
        ),
    ]
