# Generated by Django 4.1.6 on 2023-02-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='template',
            field=models.ImageField(upload_to='media'),
        ),
    ]
