# Generated by Django 4.1.6 on 2023-02-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='template',
            field=models.ImageField(upload_to='course_img'),
        ),
    ]
